apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot-service
  name: bot-service
  namespace: kube-ops

spec:
  ports:
    - name: 'bot-svc'
      nodePort: 5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: bot-service
  type: NodePort